# Generated by Django 3.2.7 on 2021-09-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=2000)),
                ('token', models.CharField(max_length=2000, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('expiry_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'URL',
            },
        ),
    ]
