# Generated by Django 3.2.7 on 2021-09-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_url_expiry_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.CharField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='token',
            field=models.CharField(max_length=5),
        ),
    ]
